version: '3.8'
services:
  php-apache-environment:
    container_name: php-apache
    build:
      context: .
      dockerfile: /docker/php-apache/Dockerfile
    depends_on:
      - db
    volumes:
      - .:/var/www/html/
    ports:
      - "8000:80"
  db:
    container_name: db
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: This_is_1!
      MYSQL_DATABASE: main
      MYSQL_USER: kostas
      MYSQL_PASSWORD: This_is_1!
    ports:
      - "9906:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    restart: always
    environment:
      PMA_HOST: db
    depends_on:
      - db